{{- if .Values.alertmanager.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cortex.alertmanagerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.alertmanagerLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
  annotations:
    {{- toYaml .Values.alertmanager.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.alertmanager.replicas }}
  selector:
    matchLabels:
      {{- include "cortex.alertmanagerSelectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.alertmanager.statefulStrategy | nindent 4 }}
  serviceName: {{ template "cortex.fullname" . }}-alertmanager-headless
  volumeClaimTemplates:
    - metadata:
        name: storage
        {{- if .Values.alertmanager.persistentVolume.annotations }}
        annotations:
          {{ toYaml .Values.alertmanager.persistentVolume.annotations | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.alertmanager.persistentVolume.storageClass }}
        {{- if (eq "-" .Values.alertmanager.persistentVolume.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.alertmanager.persistentVolume.storageClass }}"
        {{- end }}
        {{- end }}
        accessModes:
          {{ toYaml .Values.alertmanager.persistentVolume.accessModes | nindent 10 }}
        resources:
          requests:
            storage: "{{ .Values.alertmanager.persistentVolume.size }}"
  template:
    metadata:
      labels:
        {{- include "cortex.alertmanagerLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: memberlist
        {{- with .Values.alertmanager.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include "cortex.configChecksum" . }}
        {{- with .Values.alertmanager.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.alertmanager.serviceAccount.name | default (include "cortex.serviceAccountName" . ) }}
      {{- if .Values.alertmanager.priorityClassName }}
      priorityClassName: {{ .Values.alertmanager.priorityClassName }}
      {{- end }}
      {{- if .Values.alertmanager.securityContext.enabled }}
      securityContext: {{- omit .Values.alertmanager.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- toYaml .Values.alertmanager.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.alertmanager.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.alertmanager.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.alertmanager.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.alertmanager.terminationGracePeriodSeconds }}
      volumes:
        {{- include "cortex.configVolume" . | nindent 8 }}
        - name: runtime-config
          configMap:
            name: {{ template "cortex.fullname" . }}-runtime-config
        {{- if .Values.alertmanager.extraVolumes }}
        {{- toYaml .Values.alertmanager.extraVolumes | nindent 8 }}
        {{- end }}
      containers:
        {{- if .Values.alertmanager.extraContainers }}
        {{ toYaml .Values.alertmanager.extraContainers | nindent 8 }}
        {{- end }}
        - name: alertmanager
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=alertmanager"
            - "-config.file=/etc/cortex/cortex.yaml"
            {{- if .Values.minio.enabled }}
            - -alertmanager-storage.backend=s3
            - -alertmanager-storage.s3.endpoint={{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:9000
            {{- with (index .Values.minio.buckets 2) }}
            - -alertmanager-storage.s3.bucket-name={{ .name }}
            {{- end }}
            - -alertmanager-storage.s3.access-key-id={{ .Values.minio.accessKey }}
            - -alertmanager-storage.s3.secret-access-key={{ .Values.minio.secretKey }}
            - -alertmanager-storage.s3.insecure=true
            {{- end }}
            {{- range $key, $value := .Values.alertmanager.extraArgs }}
            - "-{{ $key }}={{ $value }}"
            {{- end }}
          volumeMounts:
            {{- if .Values.alertmanager.extraVolumeMounts }}
            {{- toYaml .Values.alertmanager.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/cortex
            - name: runtime-config
              mountPath: /etc/cortex/runtime
            - name: storage
              mountPath: "/data"
              {{- with .Values.alertmanager.persistentVolume.subPath }}
              subPath: {{ . }}
              {{- end }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.config.server.http_listen_port }}
              protocol: TCP
            - name: gossip
              containerPort: {{ .Values.config.memberlist.bind_port }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.alertmanager.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.alertmanager.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.alertmanager.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}
          {{- if .Values.alertmanager.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.alertmanager.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.alertmanager.env }}
          env:
            {{- toYaml .Values.alertmanager.env | nindent 12 }}
          {{- end }}
{{- end -}}
